---
# set default to true to immediately publish articles by default or false to require approval
default: false

# rules to override the default
override:

  # override and publish, these rules are not checked if the default is 1
  publish:
    # keys are properties in EIF json, values are patterns to match against an articles value of that property
    # if any pattern matches the article will be publised immediately, regardless of default setting
    doi:
     - 000000000353$
    #article-type:
    #  - research-article$

  # override and hold, these rules are not checked if the default is 0
  hold:
    # keys are properties in EIF json, values are patterns to match against an articles value of that property
    # if any pattern matches the article will be publised immediately, regardless of default setting
    doi:
      - 0000000000001$
      #- 00288$











